config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"


  resources :artists, only: [:index, :show, :destroy] do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true
  validates :born, presence: true

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show]
  def index
    @artist = Artist.all
  end

  def show
  end

  def new
    @artist  = Artist.new
  end

  def create
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist, only: [:show, :new, :create]
  def index
    @song = Song.all
  end

  def show
    @song = @artist.songs.find(params[:id])
  end

  def new
    @song = @artist.songs.new
  end

  def create

    @song = @artist.songs.build(song_params)

    if @song.save
      redirect_to artist_path(@artist), notice: "song was successfully created"
    else
      render "new", notice: "Song has not been saved"
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

      if @song.update_attributes(song_params)
        redirect_to @artist, notice: "Song was successfully updated"
      else
        render "edit"
      end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to artist_path
  end

  private
    def song_params
      params.require(:song).permit(:title, :genre, :artist_id)
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artist.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

app/views/artists/show.html.erb
<h1 class="text-center"><%= @artist.name %></h1>


<%= image_tag @artist.picture, class: "img img-circle img-responsive center-block" %>
<p><%= @artist.name %></p>
<p>born: <%= @artist.born.to_date %></p>
<p>died: <%= @artist.died.to_date %></p>
<p>About the artist: <%= @artist.bio %></p>

<h4>Songs</h4>

<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
      <li><%=link_to song.title, artist_song_path(song.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This artist doesn't have any songs.</p>
<% end %>

<%= link_to "Add a Song", new_artist_song_path(@artist.id), class: " btn btn-default" %>
<%= link_to "Delete", artist_path(@artist.id), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>

    <div class="container">
      <% if notice.present? %>
        <p class="alert alert-info" role="alert"><%= notice %></p>
      <% elsif alert.present? %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>

      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<html>

<body background="http://res.cloudinary.com/den2bvoo7/image/upload/c_fit,h_700,w_1562/v1489944597/home_background_iys9c6.jpg">
<h1>Codaisseurify</h1>

<background
</body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%=link_to "Codaisseurify", root_path, class: "navbar-brand"%></li>
      </div>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Artists", artists_path%></li>
          
        </ul>
      </div>
    </div>
  </nav>
</nav>

app/views/songs/_form.html.erb
    <%= form_for [@artist, @song] do |f| %>

      <div class="form-group">
        <p><%= f.label :title %></p>
        <p><%= f.text_field :title %></p>
      </div>

      <div class="form-group">
        <p><%= f.label :Genre %></p>
        <p><%= f.text_field :genre %></p>
      </div>


      <div class="actions">
        <p><%= f.submit "Create" %></p>
      </div>
    <%end%>

app/views/songs/edit.html.erb
<h1> Edit an existing song </h1>
<%= render "form"%>

app/views/songs/index.html.erb
<h1>Songs</h1>

<% @song.each do |song| %>
  <p><%= link_to song.title, artist_songs_path(song.id) %></p>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render "form" %>

app/views/songs/show.html.erb
  <h1><%= @song.title %></h1>

  <p>Genre: <%= @song.genre %></p>
  <p>Artist: <%= @song.artist.name %></p>
  <p>About the artist: <%= @song.artist.bio %></p>





<%= link_to "Edit", edit_artist_song_path, class: " btn btn-default" %>
<%= link_to "Delete", artist_song_path, class: " btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>